#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
init_bundle.py — Bootstrap an OKF knowledge bundle in a fresh workspace.

Run once per workspace. It:
  1. Picks a dialect preset (okf-pure default, or obsidian via --dialect).
  2. Scans the workspace to propose scan_dirs (top-level dirs that contain .md
     files) and domain rules (one per proposed scan dir).
  3. Writes okf.config.json at the workspace root.
  4. Creates the empty bundle skeleton: <bundle>/{concepts,indexes}/,
     <bundle>/_meta.json, index.md, log.md.

Idempotent-ish: refuses to overwrite an existing okf.config.json unless --force.
The skeleton is only created where missing.

Usage:
  python init_bundle.py --vault . [--dialect okf-pure|obsidian]
                        [--bundle-dir wiki] [--force] [--print]

`--print` previews the proposed config without writing anything.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PRESETS_DIR = SCRIPT_DIR.parent / "presets"
CST = timezone(timedelta(hours=8))

# Dirs never proposed as scan_dirs / domains.
SKIP_DIRS = {
    ".git", ".obsidian", ".claude", "node_modules", "assets",
    ".trash", "回收站", "wiki", "ai-output", ".vscode", ".idea",
}


def iso_now() -> str:
    return datetime.now(CST).strftime("%Y-%m-%dT%H:%M:%S+08:00")


def today() -> str:
    return datetime.now(CST).strftime("%Y-%m-%d")


def load_preset(dialect: str) -> dict:
    path = PRESETS_DIR / f"okf.config.{dialect}.json"
    if not path.is_file():
        print(f"ERROR: preset not found: {path}", file=sys.stderr)
        sys.exit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def dir_has_md(d: Path) -> bool:
    try:
        for p in d.rglob("*.md"):
            return True
    except OSError:
        pass
    return False


def propose_scan_dirs(vault: Path) -> list[str]:
    out = []
    for child in sorted(vault.iterdir()):
        if not child.is_dir() or child.name in SKIP_DIRS or child.name.startswith("."):
            continue
        if dir_has_md(child):
            out.append(child.name)
    # Fall back to scanning the whole workspace if no md-bearing subdir was found
    # but the root itself has .md files.
    if not out and any(vault.glob("*.md")):
        out.append(".")
    return out


def propose_domains(scan_dirs: list[str], default_domain: str) -> dict:
    rules = [{"path_prefix": f"{d}/", "domain": d} for d in scan_dirs if d != "."]
    return {"rules": rules, "default": default_domain}


def build_config(preset: dict, bundle_dir: str, scan_dirs: list[str]) -> dict:
    cfg = dict(preset)
    cfg["bundle_dir"] = bundle_dir
    cfg["scan_dirs"] = scan_dirs
    cfg["domains"] = propose_domains(scan_dirs, preset.get("domains", {}).get("default", "general"))
    return cfg


def write_skeleton(vault: Path, bundle_dir: str, scan_dirs: list[str], lang: str) -> list[str]:
    created = []
    bundle = vault / bundle_dir
    for sub in ("", "concepts", "indexes"):
        d = bundle / sub if sub else bundle
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(str(d.relative_to(vault)).replace("\\", "/") + "/")

    meta_path = bundle / "_meta.json"
    if not meta_path.exists():
        meta = {
            "version": "1.0",
            "created": today(),
            "last_compile": None,
            "last_lint": None,
            "compile_stats": {"total_source_files": 0, "total_concepts": 0, "domains": {}},
            "scan_dirs": scan_dirs,
            "files": {},
            "concepts": {},
        }
        meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        created.append(str(meta_path.relative_to(vault)).replace("\\", "/"))

    index_path = bundle / "index.md"
    if not index_path.exists():
        if lang == "zh":
            body = ("---\ntitle: 知识库主索引\ntype: index\n---\n\n# 知识库主索引\n\n"
                    "> 由 wiki-compile 自动生成。运行 `/wiki-compile` 后此处会列出业务域路由。\n\n"
                    "**统计**：0 个概念｜0 个业务域\n\n## 按业务域导航\n\n"
                    "| 业务域 | 概念数 | 子索引 |\n|--------|--------|--------|\n")
        else:
            body = ("---\ntitle: Knowledge Base Index\ntype: index\n---\n\n# Knowledge Base Index\n\n"
                    "> Auto-generated by wiki-compile. Run `/wiki-compile` to populate the domain router.\n\n"
                    "**Stats**: 0 concepts | 0 domains\n\n## Domains\n\n"
                    "| Domain | Concepts | Sub-index |\n|--------|----------|-----------|\n")
        index_path.write_text(body, encoding="utf-8")
        created.append(str(index_path.relative_to(vault)).replace("\\", "/"))

    log_path = bundle / "log.md"
    if not log_path.exists():
        log_path.write_text(
            f"# Knowledge Base Log\n\n## [{today()}] init | bundle bootstrapped\n\n"
            f"- bundle_dir: {bundle_dir}\n- scan_dirs: {', '.join(scan_dirs) or '(none)'}\n",
            encoding="utf-8",
        )
        created.append(str(log_path.relative_to(vault)).replace("\\", "/"))

    return created


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vault", default=".")
    ap.add_argument("--dialect", default="okf-pure", choices=["okf-pure", "obsidian"])
    ap.add_argument("--bundle-dir", default="wiki")
    ap.add_argument("--force", action="store_true", help="overwrite existing okf.config.json")
    ap.add_argument("--print", dest="preview", action="store_true",
                    help="preview proposed config without writing")
    args = ap.parse_args()

    vault = Path(args.vault).resolve()
    if not vault.is_dir():
        print(f"ERROR: workspace not found: {vault}", file=sys.stderr)
        return 1

    preset = load_preset(args.dialect)
    scan_dirs = propose_scan_dirs(vault)
    cfg = build_config(preset, args.bundle_dir, scan_dirs)

    sys.stdout.reconfigure(encoding="utf-8")
    cfg_path = vault / "okf.config.json"

    if args.preview:
        print(f"# proposed {cfg_path}")
        print(json.dumps(cfg, ensure_ascii=False, indent=2))
        print(f"\n# scan_dirs proposed: {scan_dirs or '(none — root .md only)'}")
        return 0

    if cfg_path.exists() and not args.force:
        print(f"okf.config.json already exists at {cfg_path} — pass --force to overwrite.",
              file=sys.stderr)
        return 2

    cfg_path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {cfg_path}  (dialect={args.dialect})")

    created = write_skeleton(vault, args.bundle_dir, scan_dirs, preset.get("output_language", "en"))
    print(f"Bundle skeleton under {args.bundle_dir}/:")
    for c in created:
        print(f"  + {c}")
    if not created:
        print("  (already present — nothing created)")
    print(f"\nProposed scan_dirs: {scan_dirs or '(none — add yours to okf.config.json)'}")
    print("Next: review okf.config.json, then run /wiki-compile.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
